name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pip-tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools

      - name: Update requirements files
        run: |
          # Update base requirements
          if [ -f requirements.in ]; then
            pip-compile --upgrade requirements.in
          fi
          
          # Update test requirements
          if [ -f requirements-test.in ]; then
            pip-compile --upgrade requirements-test.in
          elif [ -f requirements-test.txt ]; then
            pip-compile --upgrade --output-file requirements-test.txt requirements-test.txt
          fi
          
          # Update client requirements
          if [ -f requirements-client.in ]; then
            pip-compile --upgrade requirements-client.in
          elif [ -f requirements-client.txt ]; then
            pip-compile --upgrade --output-file requirements-client.txt requirements-client.txt
          fi

      - name: Run security audit
        run: |
          pip install safety
          safety check --output json --output safety-audit.json || true

      - name: Check for updates
        id: check-updates
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "updates=true" >> $GITHUB_OUTPUT
            echo "Updates found"
          else
            echo "updates=false" >> $GITHUB_OUTPUT
            echo "No updates found"
          fi

      - name: Create Pull Request
        if: steps.check-updates.outputs.updates == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update dependencies"
          title: "🔄 Automated dependency updates"
          body: |
            ## 🔄 Automated Dependency Updates
            
            This PR contains automated updates to project dependencies.
            
            ### Changes Made:
            - Updated Python package dependencies
            - Ran security audit (see artifacts)
            
            ### What to Review:
            - Check for any breaking changes in updated packages
            - Review the security audit results
            - Ensure all tests pass
            
            ### Generated by:
            - Workflow: `.github/workflows/dependencies.yml`
            - Triggered: ${{ github.event_name }}
            
            ---
            🤖 This PR was created automatically by GitHub Actions
          branch: automated-dependency-updates
          delete-branch: true
          labels: |
            dependencies
            automated
            
      - name: Upload security audit
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: security-audit
          path: safety-audit.json
